<?php
/**
 * CouponsResource
 * PHP version 8.1
 *
 * @category Class
 * @package  ProxyRequest
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Proxy Public API
 *
 * Reference for the customer-facing HTTP API. Request and response examples use synthetic values but follow the payloads returned by the service. Authenticate customer requests with a JWT or API key in the Authorization header.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.23.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace ProxyRequest\Resource;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use Psr\Http\Message\RequestInterface;
use Psr\Http\Message\ResponseInterface;
use ProxyRequest\ApiException;
use ProxyRequest\Configuration;
use ProxyRequest\FormDataProcessor;
use ProxyRequest\HeaderSelector;
use ProxyRequest\ObjectSerializer;

/**
 * CouponsResource Class Doc Comment
 *
 * @category Class
 * @package  ProxyRequest
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class CouponsResource
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /** @var string[] $contentTypes **/
    public const contentTypes = [
        'calculatePrice' => [
            'application/json',
            'application/x-www-form-urlencoded',
            'multipart/form-data',
        ],
        'create' => [
            'application/json',
            'application/x-www-form-urlencoded',
            'multipart/form-data',
        ],
        'delete' => [
            'application/json',
        ],
        'get' => [
            'application/json',
        ],
        'list' => [
            'application/json',
        ],
        'listRedeems' => [
            'application/json',
        ],
        'replace' => [
            'application/json',
            'application/x-www-form-urlencoded',
            'multipart/form-data',
        ],
        'update' => [
            'application/json',
            'application/x-www-form-urlencoded',
            'multipart/form-data',
        ],
    ];

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ?ClientInterface $client = null,
        ?Configuration $config = null,
        ?HeaderSelector $selector = null,
        int $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: Configuration::getDefaultConfiguration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation calculatePrice
     *
     * Calculate a discounted price
     *
     * @param  \ProxyRequest\Dto\CouponCalculatePriceRequest $couponCalculatePriceRequest couponCalculatePriceRequest (required)
     * @param  string|null $acceptLanguage Preferred language for human-readable API errors. Supported languages: en, ru, uk, de, it, fr, es, zh-hans, ja. Regional language tags and quality weights are accepted; unsupported or omitted values use English. (optional, default to 'en')
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['calculatePrice'] to see the possible values for this operation
     *
     * @throws \ProxyRequest\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \ProxyRequest\Dto\CouponPriceResponse|\ProxyRequest\Dto\AffiliatesList401Response|\ProxyRequest\Dto\AffiliatesList401Response|\ProxyRequest\Dto\AffiliatesList401Response
     */
    public function calculatePrice($couponCalculatePriceRequest, $acceptLanguage = null, string $contentType = self::contentTypes['calculatePrice'][0])
    {
        list($response) = $this->calculatePriceWithHttpInfo($couponCalculatePriceRequest, $acceptLanguage, $contentType);
        return $response;
    }

    /**
     * Operation calculatePriceWithResponse
     *
     * @return \ProxyRequest\ApiResponse
     */
    public function calculatePriceWithResponse($couponCalculatePriceRequest, $acceptLanguage = null, string $contentType = self::contentTypes['calculatePrice'][0]): \ProxyRequest\ApiResponse
    {
        return \ProxyRequest\ApiResponse::fromHttpInfo($this->calculatePriceWithHttpInfo($couponCalculatePriceRequest, $acceptLanguage, $contentType));
    }

    /**
     * Operation calculatePriceWithHttpInfo
     *
     * Calculate a discounted price
     *
     * @param  \ProxyRequest\Dto\CouponCalculatePriceRequest $couponCalculatePriceRequest (required)
     * @param  string|null $acceptLanguage Preferred language for human-readable API errors. Supported languages: en, ru, uk, de, it, fr, es, zh-hans, ja. Regional language tags and quality weights are accepted; unsupported or omitted values use English. (optional, default to 'en')
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['calculatePrice'] to see the possible values for this operation
     *
     * @throws \ProxyRequest\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \ProxyRequest\Dto\CouponPriceResponse|\ProxyRequest\Dto\AffiliatesList401Response|\ProxyRequest\Dto\AffiliatesList401Response|\ProxyRequest\Dto\AffiliatesList401Response, HTTP status code, HTTP response headers (array of strings)
     */
    public function calculatePriceWithHttpInfo($couponCalculatePriceRequest, $acceptLanguage = null, string $contentType = self::contentTypes['calculatePrice'][0])
    {
        $request = $this->calculatePriceRequest($couponCalculatePriceRequest, $acceptLanguage, $contentType);
        return \ProxyRequest\Support\ResponseHandler::send($this->client, $request, $this->createHttpClientOption(), array (
  200 => '\\ProxyRequest\\Dto\\CouponPriceResponse',
));
    }

    /**
     * Operation calculatePriceAsync
     *
     * Calculate a discounted price
     *
     * @param  \ProxyRequest\Dto\CouponCalculatePriceRequest $couponCalculatePriceRequest (required)
     * @param  string|null $acceptLanguage Preferred language for human-readable API errors. Supported languages: en, ru, uk, de, it, fr, es, zh-hans, ja. Regional language tags and quality weights are accepted; unsupported or omitted values use English. (optional, default to 'en')
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['calculatePrice'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function calculatePriceAsync($couponCalculatePriceRequest, $acceptLanguage = null, string $contentType = self::contentTypes['calculatePrice'][0])
    {
        return $this->calculatePriceAsyncWithHttpInfo($couponCalculatePriceRequest, $acceptLanguage, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation calculatePriceAsyncWithHttpInfo
     *
     * Calculate a discounted price
     *
     * @param  \ProxyRequest\Dto\CouponCalculatePriceRequest $couponCalculatePriceRequest (required)
     * @param  string|null $acceptLanguage Preferred language for human-readable API errors. Supported languages: en, ru, uk, de, it, fr, es, zh-hans, ja. Regional language tags and quality weights are accepted; unsupported or omitted values use English. (optional, default to 'en')
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['calculatePrice'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function calculatePriceAsyncWithHttpInfo($couponCalculatePriceRequest, $acceptLanguage = null, string $contentType = self::contentTypes['calculatePrice'][0])
    {
        $request = $this->calculatePriceRequest($couponCalculatePriceRequest, $acceptLanguage, $contentType);
        return \ProxyRequest\Support\ResponseHandler::sendAsync($this->client, $request, $this->createHttpClientOption(), array (
  200 => '\\ProxyRequest\\Dto\\CouponPriceResponse',
));
    }

    /**
     * Create request for operation 'calculatePrice'
     *
     * @param  \ProxyRequest\Dto\CouponCalculatePriceRequest $couponCalculatePriceRequest (required)
     * @param  string|null $acceptLanguage Preferred language for human-readable API errors. Supported languages: en, ru, uk, de, it, fr, es, zh-hans, ja. Regional language tags and quality weights are accepted; unsupported or omitted values use English. (optional, default to 'en')
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['calculatePrice'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function calculatePriceRequest($couponCalculatePriceRequest, $acceptLanguage = null, string $contentType = self::contentTypes['calculatePrice'][0])
    {

        // verify the required parameter 'couponCalculatePriceRequest' is set
        if ($couponCalculatePriceRequest === null || (is_array($couponCalculatePriceRequest) && count($couponCalculatePriceRequest) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $couponCalculatePriceRequest when calling calculatePrice'
            );
        }



        $resourcePath = '/coupons/calculate-price';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;


        // header params
        if ($acceptLanguage !== null) {
            $headerParams['Accept-Language'] = ObjectSerializer::toHeaderValue($acceptLanguage);
        }



        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($couponCalculatePriceRequest)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \ProxyRequest\Support\Json::encode(ObjectSerializer::sanitizeForSerialization($couponCalculatePriceRequest));
            } else {
                $httpBody = $couponCalculatePriceRequest;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \ProxyRequest\Support\Json::encode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Authorization');
        if ($apiKey !== null) {
            $headers['Authorization'] = $apiKey;
        }
        // this endpoint requires Bearer (JWT) authentication (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation create
     *
     * Create a coupon
     *
     * @param  \ProxyRequest\Dto\CouponCreateRequest $couponCreateRequest couponCreateRequest (required)
     * @param  string|null $idempotencyKey Stable key for one logical mutation. Successful responses are replayable for 24 hours; reusing a key with a different request returns 409. (optional)
     * @param  string|null $acceptLanguage Preferred language for human-readable API errors. Supported languages: en, ru, uk, de, it, fr, es, zh-hans, ja. Regional language tags and quality weights are accepted; unsupported or omitted values use English. (optional, default to 'en')
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['create'] to see the possible values for this operation
     *
     * @throws \ProxyRequest\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \ProxyRequest\Dto\Coupon|\ProxyRequest\Dto\AffiliatesList401Response|\ProxyRequest\Dto\AffiliatesList401Response|\ProxyRequest\Dto\AffiliatesList401Response|\ProxyRequest\Dto\AffiliatesList401Response
     */
    public function create($couponCreateRequest, $idempotencyKey = null, $acceptLanguage = null, string $contentType = self::contentTypes['create'][0])
    {
        list($response) = $this->createWithHttpInfo($couponCreateRequest, $idempotencyKey, $acceptLanguage, $contentType);
        return $response;
    }

    /**
     * Operation createWithResponse
     *
     * @return \ProxyRequest\ApiResponse
     */
    public function createWithResponse($couponCreateRequest, $idempotencyKey = null, $acceptLanguage = null, string $contentType = self::contentTypes['create'][0]): \ProxyRequest\ApiResponse
    {
        return \ProxyRequest\ApiResponse::fromHttpInfo($this->createWithHttpInfo($couponCreateRequest, $idempotencyKey, $acceptLanguage, $contentType));
    }

    /**
     * Operation createWithHttpInfo
     *
     * Create a coupon
     *
     * @param  \ProxyRequest\Dto\CouponCreateRequest $couponCreateRequest (required)
     * @param  string|null $idempotencyKey Stable key for one logical mutation. Successful responses are replayable for 24 hours; reusing a key with a different request returns 409. (optional)
     * @param  string|null $acceptLanguage Preferred language for human-readable API errors. Supported languages: en, ru, uk, de, it, fr, es, zh-hans, ja. Regional language tags and quality weights are accepted; unsupported or omitted values use English. (optional, default to 'en')
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['create'] to see the possible values for this operation
     *
     * @throws \ProxyRequest\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \ProxyRequest\Dto\Coupon|\ProxyRequest\Dto\AffiliatesList401Response|\ProxyRequest\Dto\AffiliatesList401Response|\ProxyRequest\Dto\AffiliatesList401Response|\ProxyRequest\Dto\AffiliatesList401Response, HTTP status code, HTTP response headers (array of strings)
     */
    public function createWithHttpInfo($couponCreateRequest, $idempotencyKey = null, $acceptLanguage = null, string $contentType = self::contentTypes['create'][0])
    {
        $request = $this->createRequest($couponCreateRequest, $idempotencyKey, $acceptLanguage, $contentType);
        return \ProxyRequest\Support\ResponseHandler::send($this->client, $request, $this->createHttpClientOption(), array (
  201 => '\\ProxyRequest\\Dto\\Coupon',
));
    }

    /**
     * Operation createAsync
     *
     * Create a coupon
     *
     * @param  \ProxyRequest\Dto\CouponCreateRequest $couponCreateRequest (required)
     * @param  string|null $idempotencyKey Stable key for one logical mutation. Successful responses are replayable for 24 hours; reusing a key with a different request returns 409. (optional)
     * @param  string|null $acceptLanguage Preferred language for human-readable API errors. Supported languages: en, ru, uk, de, it, fr, es, zh-hans, ja. Regional language tags and quality weights are accepted; unsupported or omitted values use English. (optional, default to 'en')
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['create'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function createAsync($couponCreateRequest, $idempotencyKey = null, $acceptLanguage = null, string $contentType = self::contentTypes['create'][0])
    {
        return $this->createAsyncWithHttpInfo($couponCreateRequest, $idempotencyKey, $acceptLanguage, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation createAsyncWithHttpInfo
     *
     * Create a coupon
     *
     * @param  \ProxyRequest\Dto\CouponCreateRequest $couponCreateRequest (required)
     * @param  string|null $idempotencyKey Stable key for one logical mutation. Successful responses are replayable for 24 hours; reusing a key with a different request returns 409. (optional)
     * @param  string|null $acceptLanguage Preferred language for human-readable API errors. Supported languages: en, ru, uk, de, it, fr, es, zh-hans, ja. Regional language tags and quality weights are accepted; unsupported or omitted values use English. (optional, default to 'en')
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['create'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function createAsyncWithHttpInfo($couponCreateRequest, $idempotencyKey = null, $acceptLanguage = null, string $contentType = self::contentTypes['create'][0])
    {
        $request = $this->createRequest($couponCreateRequest, $idempotencyKey, $acceptLanguage, $contentType);
        return \ProxyRequest\Support\ResponseHandler::sendAsync($this->client, $request, $this->createHttpClientOption(), array (
  201 => '\\ProxyRequest\\Dto\\Coupon',
));
    }

    /**
     * Create request for operation 'create'
     *
     * @param  \ProxyRequest\Dto\CouponCreateRequest $couponCreateRequest (required)
     * @param  string|null $idempotencyKey Stable key for one logical mutation. Successful responses are replayable for 24 hours; reusing a key with a different request returns 409. (optional)
     * @param  string|null $acceptLanguage Preferred language for human-readable API errors. Supported languages: en, ru, uk, de, it, fr, es, zh-hans, ja. Regional language tags and quality weights are accepted; unsupported or omitted values use English. (optional, default to 'en')
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['create'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function createRequest($couponCreateRequest, $idempotencyKey = null, $acceptLanguage = null, string $contentType = self::contentTypes['create'][0])
    {

        // verify the required parameter 'couponCreateRequest' is set
        if ($couponCreateRequest === null || (is_array($couponCreateRequest) && count($couponCreateRequest) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $couponCreateRequest when calling create'
            );
        }

        if ($idempotencyKey !== null && strlen($idempotencyKey) > 255) {
            throw new \InvalidArgumentException('invalid length for "$idempotencyKey" when calling CouponsResource.create, must be smaller than or equal to 255.');
        }



        $resourcePath = '/coupons';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;


        // header params
        if ($idempotencyKey !== null) {
            $headerParams['Idempotency-Key'] = ObjectSerializer::toHeaderValue($idempotencyKey);
        }
        // header params
        if ($acceptLanguage !== null) {
            $headerParams['Accept-Language'] = ObjectSerializer::toHeaderValue($acceptLanguage);
        }



        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($couponCreateRequest)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \ProxyRequest\Support\Json::encode(ObjectSerializer::sanitizeForSerialization($couponCreateRequest));
            } else {
                $httpBody = $couponCreateRequest;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \ProxyRequest\Support\Json::encode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Authorization');
        if ($apiKey !== null) {
            $headers['Authorization'] = $apiKey;
        }
        // this endpoint requires Bearer (JWT) authentication (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation delete
     *
     * Delete a coupon
     *
     * @param  string $id A unique value identifying this Coupon. (required)
     * @param  string|null $idempotencyKey Stable key for one logical mutation. Successful responses are replayable for 24 hours; reusing a key with a different request returns 409. (optional)
     * @param  string|null $ifMatch Strong ETag from the latest representation of this resource. (optional)
     * @param  string|null $acceptLanguage Preferred language for human-readable API errors. Supported languages: en, ru, uk, de, it, fr, es, zh-hans, ja. Regional language tags and quality weights are accepted; unsupported or omitted values use English. (optional, default to 'en')
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['delete'] to see the possible values for this operation
     *
     * @throws \ProxyRequest\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return void
     */
    public function delete($id, $idempotencyKey = null, $ifMatch = null, $acceptLanguage = null, string $contentType = self::contentTypes['delete'][0])
    {
        $this->deleteWithHttpInfo($id, $idempotencyKey, $ifMatch, $acceptLanguage, $contentType);
    }

    /**
     * Operation deleteWithResponse
     *
     * @return \ProxyRequest\ApiResponse
     */
    public function deleteWithResponse($id, $idempotencyKey = null, $ifMatch = null, $acceptLanguage = null, string $contentType = self::contentTypes['delete'][0]): \ProxyRequest\ApiResponse
    {
        return \ProxyRequest\ApiResponse::fromHttpInfo($this->deleteWithHttpInfo($id, $idempotencyKey, $ifMatch, $acceptLanguage, $contentType));
    }

    /**
     * Operation deleteWithHttpInfo
     *
     * Delete a coupon
     *
     * @param  string $id A unique value identifying this Coupon. (required)
     * @param  string|null $idempotencyKey Stable key for one logical mutation. Successful responses are replayable for 24 hours; reusing a key with a different request returns 409. (optional)
     * @param  string|null $ifMatch Strong ETag from the latest representation of this resource. (optional)
     * @param  string|null $acceptLanguage Preferred language for human-readable API errors. Supported languages: en, ru, uk, de, it, fr, es, zh-hans, ja. Regional language tags and quality weights are accepted; unsupported or omitted values use English. (optional, default to 'en')
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['delete'] to see the possible values for this operation
     *
     * @throws \ProxyRequest\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function deleteWithHttpInfo($id, $idempotencyKey = null, $ifMatch = null, $acceptLanguage = null, string $contentType = self::contentTypes['delete'][0])
    {
        $request = $this->deleteRequest($id, $idempotencyKey, $ifMatch, $acceptLanguage, $contentType);
        return \ProxyRequest\Support\ResponseHandler::send($this->client, $request, $this->createHttpClientOption(), array (
  204 => 'void',
));
    }

    /**
     * Operation deleteAsync
     *
     * Delete a coupon
     *
     * @param  string $id A unique value identifying this Coupon. (required)
     * @param  string|null $idempotencyKey Stable key for one logical mutation. Successful responses are replayable for 24 hours; reusing a key with a different request returns 409. (optional)
     * @param  string|null $ifMatch Strong ETag from the latest representation of this resource. (optional)
     * @param  string|null $acceptLanguage Preferred language for human-readable API errors. Supported languages: en, ru, uk, de, it, fr, es, zh-hans, ja. Regional language tags and quality weights are accepted; unsupported or omitted values use English. (optional, default to 'en')
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['delete'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function deleteAsync($id, $idempotencyKey = null, $ifMatch = null, $acceptLanguage = null, string $contentType = self::contentTypes['delete'][0])
    {
        return $this->deleteAsyncWithHttpInfo($id, $idempotencyKey, $ifMatch, $acceptLanguage, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation deleteAsyncWithHttpInfo
     *
     * Delete a coupon
     *
     * @param  string $id A unique value identifying this Coupon. (required)
     * @param  string|null $idempotencyKey Stable key for one logical mutation. Successful responses are replayable for 24 hours; reusing a key with a different request returns 409. (optional)
     * @param  string|null $ifMatch Strong ETag from the latest representation of this resource. (optional)
     * @param  string|null $acceptLanguage Preferred language for human-readable API errors. Supported languages: en, ru, uk, de, it, fr, es, zh-hans, ja. Regional language tags and quality weights are accepted; unsupported or omitted values use English. (optional, default to 'en')
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['delete'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function deleteAsyncWithHttpInfo($id, $idempotencyKey = null, $ifMatch = null, $acceptLanguage = null, string $contentType = self::contentTypes['delete'][0])
    {
        $request = $this->deleteRequest($id, $idempotencyKey, $ifMatch, $acceptLanguage, $contentType);
        return \ProxyRequest\Support\ResponseHandler::sendAsync($this->client, $request, $this->createHttpClientOption(), array (
  204 => 'void',
));
    }

    /**
     * Create request for operation 'delete'
     *
     * @param  string $id A unique value identifying this Coupon. (required)
     * @param  string|null $idempotencyKey Stable key for one logical mutation. Successful responses are replayable for 24 hours; reusing a key with a different request returns 409. (optional)
     * @param  string|null $ifMatch Strong ETag from the latest representation of this resource. (optional)
     * @param  string|null $acceptLanguage Preferred language for human-readable API errors. Supported languages: en, ru, uk, de, it, fr, es, zh-hans, ja. Regional language tags and quality weights are accepted; unsupported or omitted values use English. (optional, default to 'en')
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['delete'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function deleteRequest($id, $idempotencyKey = null, $ifMatch = null, $acceptLanguage = null, string $contentType = self::contentTypes['delete'][0])
    {

        // verify the required parameter 'id' is set
        if ($id === null || (is_array($id) && count($id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $id when calling delete'
            );
        }

        if ($idempotencyKey !== null && strlen($idempotencyKey) > 255) {
            throw new \InvalidArgumentException('invalid length for "$idempotencyKey" when calling CouponsResource.delete, must be smaller than or equal to 255.');
        }




        $resourcePath = '/coupons/{id}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;


        // header params
        if ($idempotencyKey !== null) {
            $headerParams['Idempotency-Key'] = ObjectSerializer::toHeaderValue($idempotencyKey);
        }
        // header params
        if ($ifMatch !== null) {
            $headerParams['If-Match'] = ObjectSerializer::toHeaderValue($ifMatch);
        }
        // header params
        if ($acceptLanguage !== null) {
            $headerParams['Accept-Language'] = ObjectSerializer::toHeaderValue($acceptLanguage);
        }

        // path params
        if ($id !== null) {
            $resourcePath = str_replace(
                '{id}',
                ObjectSerializer::toPathValue($id),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \ProxyRequest\Support\Json::encode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Authorization');
        if ($apiKey !== null) {
            $headers['Authorization'] = $apiKey;
        }
        // this endpoint requires Bearer (JWT) authentication (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'DELETE',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation get
     *
     * Get a coupon
     *
     * @param  string $id A unique value identifying this Coupon. (required)
     * @param  string|null $acceptLanguage Preferred language for human-readable API errors. Supported languages: en, ru, uk, de, it, fr, es, zh-hans, ja. Regional language tags and quality weights are accepted; unsupported or omitted values use English. (optional, default to 'en')
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['get'] to see the possible values for this operation
     *
     * @throws \ProxyRequest\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \ProxyRequest\Dto\CouponShort|\ProxyRequest\Dto\AffiliatesList401Response|\ProxyRequest\Dto\AffiliatesList401Response|\ProxyRequest\Dto\AffiliatesList401Response|\ProxyRequest\Dto\AffiliatesList401Response
     */
    public function get($id, $acceptLanguage = null, string $contentType = self::contentTypes['get'][0])
    {
        list($response) = $this->getWithHttpInfo($id, $acceptLanguage, $contentType);
        return $response;
    }

    /**
     * Operation getWithResponse
     *
     * @return \ProxyRequest\ApiResponse
     */
    public function getWithResponse($id, $acceptLanguage = null, string $contentType = self::contentTypes['get'][0]): \ProxyRequest\ApiResponse
    {
        return \ProxyRequest\ApiResponse::fromHttpInfo($this->getWithHttpInfo($id, $acceptLanguage, $contentType));
    }

    /**
     * Operation getWithHttpInfo
     *
     * Get a coupon
     *
     * @param  string $id A unique value identifying this Coupon. (required)
     * @param  string|null $acceptLanguage Preferred language for human-readable API errors. Supported languages: en, ru, uk, de, it, fr, es, zh-hans, ja. Regional language tags and quality weights are accepted; unsupported or omitted values use English. (optional, default to 'en')
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['get'] to see the possible values for this operation
     *
     * @throws \ProxyRequest\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \ProxyRequest\Dto\CouponShort|\ProxyRequest\Dto\AffiliatesList401Response|\ProxyRequest\Dto\AffiliatesList401Response|\ProxyRequest\Dto\AffiliatesList401Response|\ProxyRequest\Dto\AffiliatesList401Response, HTTP status code, HTTP response headers (array of strings)
     */
    public function getWithHttpInfo($id, $acceptLanguage = null, string $contentType = self::contentTypes['get'][0])
    {
        $request = $this->getRequest($id, $acceptLanguage, $contentType);
        return \ProxyRequest\Support\ResponseHandler::send($this->client, $request, $this->createHttpClientOption(), array (
  200 => '\\ProxyRequest\\Dto\\CouponShort',
));
    }

    /**
     * Operation getAsync
     *
     * Get a coupon
     *
     * @param  string $id A unique value identifying this Coupon. (required)
     * @param  string|null $acceptLanguage Preferred language for human-readable API errors. Supported languages: en, ru, uk, de, it, fr, es, zh-hans, ja. Regional language tags and quality weights are accepted; unsupported or omitted values use English. (optional, default to 'en')
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['get'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getAsync($id, $acceptLanguage = null, string $contentType = self::contentTypes['get'][0])
    {
        return $this->getAsyncWithHttpInfo($id, $acceptLanguage, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getAsyncWithHttpInfo
     *
     * Get a coupon
     *
     * @param  string $id A unique value identifying this Coupon. (required)
     * @param  string|null $acceptLanguage Preferred language for human-readable API errors. Supported languages: en, ru, uk, de, it, fr, es, zh-hans, ja. Regional language tags and quality weights are accepted; unsupported or omitted values use English. (optional, default to 'en')
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['get'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getAsyncWithHttpInfo($id, $acceptLanguage = null, string $contentType = self::contentTypes['get'][0])
    {
        $request = $this->getRequest($id, $acceptLanguage, $contentType);
        return \ProxyRequest\Support\ResponseHandler::sendAsync($this->client, $request, $this->createHttpClientOption(), array (
  200 => '\\ProxyRequest\\Dto\\CouponShort',
));
    }

    /**
     * Create request for operation 'get'
     *
     * @param  string $id A unique value identifying this Coupon. (required)
     * @param  string|null $acceptLanguage Preferred language for human-readable API errors. Supported languages: en, ru, uk, de, it, fr, es, zh-hans, ja. Regional language tags and quality weights are accepted; unsupported or omitted values use English. (optional, default to 'en')
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['get'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function getRequest($id, $acceptLanguage = null, string $contentType = self::contentTypes['get'][0])
    {

        // verify the required parameter 'id' is set
        if ($id === null || (is_array($id) && count($id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $id when calling get'
            );
        }



        $resourcePath = '/coupons/{id}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;


        // header params
        if ($acceptLanguage !== null) {
            $headerParams['Accept-Language'] = ObjectSerializer::toHeaderValue($acceptLanguage);
        }

        // path params
        if ($id !== null) {
            $resourcePath = str_replace(
                '{id}',
                ObjectSerializer::toPathValue($id),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \ProxyRequest\Support\Json::encode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Authorization');
        if ($apiKey !== null) {
            $headers['Authorization'] = $apiKey;
        }
        // this endpoint requires Bearer (JWT) authentication (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation list
     *
     * List available coupons
     *
     * @param  string|null $code code (optional)
     * @param  int|null $limit Number of results to return per page. (optional)
     * @param  int|null $offset The initial index from which to return the results. (optional)
     * @param  string|null $ordering Which field to use when ordering the results. (optional)
     * @param  string|null $search Case-insensitive partial search across Coupon fields: &#x60;title&#x60; and &#x60;content&#x60;. Separate multiple terms with spaces or commas; every term must match at least one listed field. (optional)
     * @param  string|null $type * &#x60;free_data&#x60; - Free Data * &#x60;monetary&#x60; - Money * &#x60;percentage&#x60; - Percentage (optional)
     * @param  string|null $acceptLanguage Preferred language for human-readable API errors. Supported languages: en, ru, uk, de, it, fr, es, zh-hans, ja. Regional language tags and quality weights are accepted; unsupported or omitted values use English. (optional, default to 'en')
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['list'] to see the possible values for this operation
     *
     * @throws \ProxyRequest\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \ProxyRequest\Dto\PaginatedCouponShortList|\ProxyRequest\Dto\AffiliatesList401Response|\ProxyRequest\Dto\AffiliatesList401Response|\ProxyRequest\Dto\AffiliatesList401Response
     */
    public function list($code = null, $limit = null, $offset = null, $ordering = null, $search = null, $type = null, $acceptLanguage = null, string $contentType = self::contentTypes['list'][0])
    {
        list($response) = $this->listWithHttpInfo($code, $limit, $offset, $ordering, $search, $type, $acceptLanguage, $contentType);
        return $response;
    }

    /**
     * Operation listWithResponse
     *
     * @return \ProxyRequest\ApiResponse
     */
    public function listWithResponse($code = null, $limit = null, $offset = null, $ordering = null, $search = null, $type = null, $acceptLanguage = null, string $contentType = self::contentTypes['list'][0]): \ProxyRequest\ApiResponse
    {
        return \ProxyRequest\ApiResponse::fromHttpInfo($this->listWithHttpInfo($code, $limit, $offset, $ordering, $search, $type, $acceptLanguage, $contentType));
    }

    /**
     * Operation listWithHttpInfo
     *
     * List available coupons
     *
     * @param  string|null $code (optional)
     * @param  int|null $limit Number of results to return per page. (optional)
     * @param  int|null $offset The initial index from which to return the results. (optional)
     * @param  string|null $ordering Which field to use when ordering the results. (optional)
     * @param  string|null $search Case-insensitive partial search across Coupon fields: &#x60;title&#x60; and &#x60;content&#x60;. Separate multiple terms with spaces or commas; every term must match at least one listed field. (optional)
     * @param  string|null $type * &#x60;free_data&#x60; - Free Data * &#x60;monetary&#x60; - Money * &#x60;percentage&#x60; - Percentage (optional)
     * @param  string|null $acceptLanguage Preferred language for human-readable API errors. Supported languages: en, ru, uk, de, it, fr, es, zh-hans, ja. Regional language tags and quality weights are accepted; unsupported or omitted values use English. (optional, default to 'en')
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['list'] to see the possible values for this operation
     *
     * @throws \ProxyRequest\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \ProxyRequest\Dto\PaginatedCouponShortList|\ProxyRequest\Dto\AffiliatesList401Response|\ProxyRequest\Dto\AffiliatesList401Response|\ProxyRequest\Dto\AffiliatesList401Response, HTTP status code, HTTP response headers (array of strings)
     */
    public function listWithHttpInfo($code = null, $limit = null, $offset = null, $ordering = null, $search = null, $type = null, $acceptLanguage = null, string $contentType = self::contentTypes['list'][0])
    {
        $request = $this->listRequest($code, $limit, $offset, $ordering, $search, $type, $acceptLanguage, $contentType);
        return \ProxyRequest\Support\ResponseHandler::send($this->client, $request, $this->createHttpClientOption(), array (
  200 => '\\ProxyRequest\\Dto\\PaginatedCouponShortList',
));
    }

    /**
     * Operation listAsync
     *
     * List available coupons
     *
     * @param  string|null $code (optional)
     * @param  int|null $limit Number of results to return per page. (optional)
     * @param  int|null $offset The initial index from which to return the results. (optional)
     * @param  string|null $ordering Which field to use when ordering the results. (optional)
     * @param  string|null $search Case-insensitive partial search across Coupon fields: &#x60;title&#x60; and &#x60;content&#x60;. Separate multiple terms with spaces or commas; every term must match at least one listed field. (optional)
     * @param  string|null $type * &#x60;free_data&#x60; - Free Data * &#x60;monetary&#x60; - Money * &#x60;percentage&#x60; - Percentage (optional)
     * @param  string|null $acceptLanguage Preferred language for human-readable API errors. Supported languages: en, ru, uk, de, it, fr, es, zh-hans, ja. Regional language tags and quality weights are accepted; unsupported or omitted values use English. (optional, default to 'en')
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['list'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function listAsync($code = null, $limit = null, $offset = null, $ordering = null, $search = null, $type = null, $acceptLanguage = null, string $contentType = self::contentTypes['list'][0])
    {
        return $this->listAsyncWithHttpInfo($code, $limit, $offset, $ordering, $search, $type, $acceptLanguage, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation listAsyncWithHttpInfo
     *
     * List available coupons
     *
     * @param  string|null $code (optional)
     * @param  int|null $limit Number of results to return per page. (optional)
     * @param  int|null $offset The initial index from which to return the results. (optional)
     * @param  string|null $ordering Which field to use when ordering the results. (optional)
     * @param  string|null $search Case-insensitive partial search across Coupon fields: &#x60;title&#x60; and &#x60;content&#x60;. Separate multiple terms with spaces or commas; every term must match at least one listed field. (optional)
     * @param  string|null $type * &#x60;free_data&#x60; - Free Data * &#x60;monetary&#x60; - Money * &#x60;percentage&#x60; - Percentage (optional)
     * @param  string|null $acceptLanguage Preferred language for human-readable API errors. Supported languages: en, ru, uk, de, it, fr, es, zh-hans, ja. Regional language tags and quality weights are accepted; unsupported or omitted values use English. (optional, default to 'en')
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['list'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function listAsyncWithHttpInfo($code = null, $limit = null, $offset = null, $ordering = null, $search = null, $type = null, $acceptLanguage = null, string $contentType = self::contentTypes['list'][0])
    {
        $request = $this->listRequest($code, $limit, $offset, $ordering, $search, $type, $acceptLanguage, $contentType);
        return \ProxyRequest\Support\ResponseHandler::sendAsync($this->client, $request, $this->createHttpClientOption(), array (
  200 => '\\ProxyRequest\\Dto\\PaginatedCouponShortList',
));
    }

    /**
     * Create request for operation 'list'
     *
     * @param  string|null $code (optional)
     * @param  int|null $limit Number of results to return per page. (optional)
     * @param  int|null $offset The initial index from which to return the results. (optional)
     * @param  string|null $ordering Which field to use when ordering the results. (optional)
     * @param  string|null $search Case-insensitive partial search across Coupon fields: &#x60;title&#x60; and &#x60;content&#x60;. Separate multiple terms with spaces or commas; every term must match at least one listed field. (optional)
     * @param  string|null $type * &#x60;free_data&#x60; - Free Data * &#x60;monetary&#x60; - Money * &#x60;percentage&#x60; - Percentage (optional)
     * @param  string|null $acceptLanguage Preferred language for human-readable API errors. Supported languages: en, ru, uk, de, it, fr, es, zh-hans, ja. Regional language tags and quality weights are accepted; unsupported or omitted values use English. (optional, default to 'en')
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['list'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function listRequest($code = null, $limit = null, $offset = null, $ordering = null, $search = null, $type = null, $acceptLanguage = null, string $contentType = self::contentTypes['list'][0])
    {









        $resourcePath = '/coupons';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $code,
            'code', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $limit,
            'limit', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $offset,
            'offset', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $ordering,
            'ordering', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $search,
            'search', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $type,
            'type', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);

        // header params
        if ($acceptLanguage !== null) {
            $headerParams['Accept-Language'] = ObjectSerializer::toHeaderValue($acceptLanguage);
        }



        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \ProxyRequest\Support\Json::encode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Authorization');
        if ($apiKey !== null) {
            $headers['Authorization'] = $apiKey;
        }
        // this endpoint requires Bearer (JWT) authentication (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation listRedeems
     *
     * List coupon redemptions
     *
     * @param  string $id A unique value identifying this Coupon. (required)
     * @param  string|null $code code (optional)
     * @param  int|null $limit Number of results to return per page. (optional)
     * @param  int|null $offset The initial index from which to return the results. (optional)
     * @param  string|null $ordering Which field to use when ordering the results. (optional)
     * @param  string|null $type * &#x60;free_data&#x60; - Free Data * &#x60;monetary&#x60; - Money * &#x60;percentage&#x60; - Percentage (optional)
     * @param  string|null $acceptLanguage Preferred language for human-readable API errors. Supported languages: en, ru, uk, de, it, fr, es, zh-hans, ja. Regional language tags and quality weights are accepted; unsupported or omitted values use English. (optional, default to 'en')
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['listRedeems'] to see the possible values for this operation
     *
     * @throws \ProxyRequest\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \ProxyRequest\Dto\PaginatedCouponRedeemList|\ProxyRequest\Dto\AffiliatesList401Response|\ProxyRequest\Dto\AffiliatesList401Response|\ProxyRequest\Dto\AffiliatesList401Response|\ProxyRequest\Dto\AffiliatesList401Response
     */
    public function listRedeems($id, $code = null, $limit = null, $offset = null, $ordering = null, $type = null, $acceptLanguage = null, string $contentType = self::contentTypes['listRedeems'][0])
    {
        list($response) = $this->listRedeemsWithHttpInfo($id, $code, $limit, $offset, $ordering, $type, $acceptLanguage, $contentType);
        return $response;
    }

    /**
     * Operation listRedeemsWithResponse
     *
     * @return \ProxyRequest\ApiResponse
     */
    public function listRedeemsWithResponse($id, $code = null, $limit = null, $offset = null, $ordering = null, $type = null, $acceptLanguage = null, string $contentType = self::contentTypes['listRedeems'][0]): \ProxyRequest\ApiResponse
    {
        return \ProxyRequest\ApiResponse::fromHttpInfo($this->listRedeemsWithHttpInfo($id, $code, $limit, $offset, $ordering, $type, $acceptLanguage, $contentType));
    }

    /**
     * Operation listRedeemsWithHttpInfo
     *
     * List coupon redemptions
     *
     * @param  string $id A unique value identifying this Coupon. (required)
     * @param  string|null $code (optional)
     * @param  int|null $limit Number of results to return per page. (optional)
     * @param  int|null $offset The initial index from which to return the results. (optional)
     * @param  string|null $ordering Which field to use when ordering the results. (optional)
     * @param  string|null $type * &#x60;free_data&#x60; - Free Data * &#x60;monetary&#x60; - Money * &#x60;percentage&#x60; - Percentage (optional)
     * @param  string|null $acceptLanguage Preferred language for human-readable API errors. Supported languages: en, ru, uk, de, it, fr, es, zh-hans, ja. Regional language tags and quality weights are accepted; unsupported or omitted values use English. (optional, default to 'en')
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['listRedeems'] to see the possible values for this operation
     *
     * @throws \ProxyRequest\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \ProxyRequest\Dto\PaginatedCouponRedeemList|\ProxyRequest\Dto\AffiliatesList401Response|\ProxyRequest\Dto\AffiliatesList401Response|\ProxyRequest\Dto\AffiliatesList401Response|\ProxyRequest\Dto\AffiliatesList401Response, HTTP status code, HTTP response headers (array of strings)
     */
    public function listRedeemsWithHttpInfo($id, $code = null, $limit = null, $offset = null, $ordering = null, $type = null, $acceptLanguage = null, string $contentType = self::contentTypes['listRedeems'][0])
    {
        $request = $this->listRedeemsRequest($id, $code, $limit, $offset, $ordering, $type, $acceptLanguage, $contentType);
        return \ProxyRequest\Support\ResponseHandler::send($this->client, $request, $this->createHttpClientOption(), array (
  200 => '\\ProxyRequest\\Dto\\PaginatedCouponRedeemList',
));
    }

    /**
     * Operation listRedeemsAsync
     *
     * List coupon redemptions
     *
     * @param  string $id A unique value identifying this Coupon. (required)
     * @param  string|null $code (optional)
     * @param  int|null $limit Number of results to return per page. (optional)
     * @param  int|null $offset The initial index from which to return the results. (optional)
     * @param  string|null $ordering Which field to use when ordering the results. (optional)
     * @param  string|null $type * &#x60;free_data&#x60; - Free Data * &#x60;monetary&#x60; - Money * &#x60;percentage&#x60; - Percentage (optional)
     * @param  string|null $acceptLanguage Preferred language for human-readable API errors. Supported languages: en, ru, uk, de, it, fr, es, zh-hans, ja. Regional language tags and quality weights are accepted; unsupported or omitted values use English. (optional, default to 'en')
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['listRedeems'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function listRedeemsAsync($id, $code = null, $limit = null, $offset = null, $ordering = null, $type = null, $acceptLanguage = null, string $contentType = self::contentTypes['listRedeems'][0])
    {
        return $this->listRedeemsAsyncWithHttpInfo($id, $code, $limit, $offset, $ordering, $type, $acceptLanguage, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation listRedeemsAsyncWithHttpInfo
     *
     * List coupon redemptions
     *
     * @param  string $id A unique value identifying this Coupon. (required)
     * @param  string|null $code (optional)
     * @param  int|null $limit Number of results to return per page. (optional)
     * @param  int|null $offset The initial index from which to return the results. (optional)
     * @param  string|null $ordering Which field to use when ordering the results. (optional)
     * @param  string|null $type * &#x60;free_data&#x60; - Free Data * &#x60;monetary&#x60; - Money * &#x60;percentage&#x60; - Percentage (optional)
     * @param  string|null $acceptLanguage Preferred language for human-readable API errors. Supported languages: en, ru, uk, de, it, fr, es, zh-hans, ja. Regional language tags and quality weights are accepted; unsupported or omitted values use English. (optional, default to 'en')
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['listRedeems'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function listRedeemsAsyncWithHttpInfo($id, $code = null, $limit = null, $offset = null, $ordering = null, $type = null, $acceptLanguage = null, string $contentType = self::contentTypes['listRedeems'][0])
    {
        $request = $this->listRedeemsRequest($id, $code, $limit, $offset, $ordering, $type, $acceptLanguage, $contentType);
        return \ProxyRequest\Support\ResponseHandler::sendAsync($this->client, $request, $this->createHttpClientOption(), array (
  200 => '\\ProxyRequest\\Dto\\PaginatedCouponRedeemList',
));
    }

    /**
     * Create request for operation 'listRedeems'
     *
     * @param  string $id A unique value identifying this Coupon. (required)
     * @param  string|null $code (optional)
     * @param  int|null $limit Number of results to return per page. (optional)
     * @param  int|null $offset The initial index from which to return the results. (optional)
     * @param  string|null $ordering Which field to use when ordering the results. (optional)
     * @param  string|null $type * &#x60;free_data&#x60; - Free Data * &#x60;monetary&#x60; - Money * &#x60;percentage&#x60; - Percentage (optional)
     * @param  string|null $acceptLanguage Preferred language for human-readable API errors. Supported languages: en, ru, uk, de, it, fr, es, zh-hans, ja. Regional language tags and quality weights are accepted; unsupported or omitted values use English. (optional, default to 'en')
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['listRedeems'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function listRedeemsRequest($id, $code = null, $limit = null, $offset = null, $ordering = null, $type = null, $acceptLanguage = null, string $contentType = self::contentTypes['listRedeems'][0])
    {

        // verify the required parameter 'id' is set
        if ($id === null || (is_array($id) && count($id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $id when calling listRedeems'
            );
        }








        $resourcePath = '/coupons/{id}/redeems';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $code,
            'code', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $limit,
            'limit', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $offset,
            'offset', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $ordering,
            'ordering', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $type,
            'type', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);

        // header params
        if ($acceptLanguage !== null) {
            $headerParams['Accept-Language'] = ObjectSerializer::toHeaderValue($acceptLanguage);
        }

        // path params
        if ($id !== null) {
            $resourcePath = str_replace(
                '{id}',
                ObjectSerializer::toPathValue($id),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \ProxyRequest\Support\Json::encode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Authorization');
        if ($apiKey !== null) {
            $headers['Authorization'] = $apiKey;
        }
        // this endpoint requires Bearer (JWT) authentication (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation replace
     *
     * Replace a coupon
     *
     * @param  string $id A unique value identifying this Coupon. (required)
     * @param  \ProxyRequest\Dto\CouponUpdateRequest $couponUpdateRequest couponUpdateRequest (required)
     * @param  string|null $ifMatch Strong ETag from the latest representation of this resource. (optional)
     * @param  string|null $acceptLanguage Preferred language for human-readable API errors. Supported languages: en, ru, uk, de, it, fr, es, zh-hans, ja. Regional language tags and quality weights are accepted; unsupported or omitted values use English. (optional, default to 'en')
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['replace'] to see the possible values for this operation
     *
     * @throws \ProxyRequest\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \ProxyRequest\Dto\Coupon|\ProxyRequest\Dto\AffiliatesList401Response|\ProxyRequest\Dto\AffiliatesList401Response|\ProxyRequest\Dto\AffiliatesList401Response|\ProxyRequest\Dto\AffiliatesList401Response|\ProxyRequest\Dto\AffiliatesList401Response
     */
    public function replace($id, $couponUpdateRequest, $ifMatch = null, $acceptLanguage = null, string $contentType = self::contentTypes['replace'][0])
    {
        list($response) = $this->replaceWithHttpInfo($id, $couponUpdateRequest, $ifMatch, $acceptLanguage, $contentType);
        return $response;
    }

    /**
     * Operation replaceWithResponse
     *
     * @return \ProxyRequest\ApiResponse
     */
    public function replaceWithResponse($id, $couponUpdateRequest, $ifMatch = null, $acceptLanguage = null, string $contentType = self::contentTypes['replace'][0]): \ProxyRequest\ApiResponse
    {
        return \ProxyRequest\ApiResponse::fromHttpInfo($this->replaceWithHttpInfo($id, $couponUpdateRequest, $ifMatch, $acceptLanguage, $contentType));
    }

    /**
     * Operation replaceWithHttpInfo
     *
     * Replace a coupon
     *
     * @param  string $id A unique value identifying this Coupon. (required)
     * @param  \ProxyRequest\Dto\CouponUpdateRequest $couponUpdateRequest (required)
     * @param  string|null $ifMatch Strong ETag from the latest representation of this resource. (optional)
     * @param  string|null $acceptLanguage Preferred language for human-readable API errors. Supported languages: en, ru, uk, de, it, fr, es, zh-hans, ja. Regional language tags and quality weights are accepted; unsupported or omitted values use English. (optional, default to 'en')
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['replace'] to see the possible values for this operation
     *
     * @throws \ProxyRequest\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \ProxyRequest\Dto\Coupon|\ProxyRequest\Dto\AffiliatesList401Response|\ProxyRequest\Dto\AffiliatesList401Response|\ProxyRequest\Dto\AffiliatesList401Response|\ProxyRequest\Dto\AffiliatesList401Response|\ProxyRequest\Dto\AffiliatesList401Response, HTTP status code, HTTP response headers (array of strings)
     */
    public function replaceWithHttpInfo($id, $couponUpdateRequest, $ifMatch = null, $acceptLanguage = null, string $contentType = self::contentTypes['replace'][0])
    {
        $request = $this->replaceRequest($id, $couponUpdateRequest, $ifMatch, $acceptLanguage, $contentType);
        return \ProxyRequest\Support\ResponseHandler::send($this->client, $request, $this->createHttpClientOption(), array (
  200 => '\\ProxyRequest\\Dto\\Coupon',
));
    }

    /**
     * Operation replaceAsync
     *
     * Replace a coupon
     *
     * @param  string $id A unique value identifying this Coupon. (required)
     * @param  \ProxyRequest\Dto\CouponUpdateRequest $couponUpdateRequest (required)
     * @param  string|null $ifMatch Strong ETag from the latest representation of this resource. (optional)
     * @param  string|null $acceptLanguage Preferred language for human-readable API errors. Supported languages: en, ru, uk, de, it, fr, es, zh-hans, ja. Regional language tags and quality weights are accepted; unsupported or omitted values use English. (optional, default to 'en')
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['replace'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function replaceAsync($id, $couponUpdateRequest, $ifMatch = null, $acceptLanguage = null, string $contentType = self::contentTypes['replace'][0])
    {
        return $this->replaceAsyncWithHttpInfo($id, $couponUpdateRequest, $ifMatch, $acceptLanguage, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation replaceAsyncWithHttpInfo
     *
     * Replace a coupon
     *
     * @param  string $id A unique value identifying this Coupon. (required)
     * @param  \ProxyRequest\Dto\CouponUpdateRequest $couponUpdateRequest (required)
     * @param  string|null $ifMatch Strong ETag from the latest representation of this resource. (optional)
     * @param  string|null $acceptLanguage Preferred language for human-readable API errors. Supported languages: en, ru, uk, de, it, fr, es, zh-hans, ja. Regional language tags and quality weights are accepted; unsupported or omitted values use English. (optional, default to 'en')
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['replace'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function replaceAsyncWithHttpInfo($id, $couponUpdateRequest, $ifMatch = null, $acceptLanguage = null, string $contentType = self::contentTypes['replace'][0])
    {
        $request = $this->replaceRequest($id, $couponUpdateRequest, $ifMatch, $acceptLanguage, $contentType);
        return \ProxyRequest\Support\ResponseHandler::sendAsync($this->client, $request, $this->createHttpClientOption(), array (
  200 => '\\ProxyRequest\\Dto\\Coupon',
));
    }

    /**
     * Create request for operation 'replace'
     *
     * @param  string $id A unique value identifying this Coupon. (required)
     * @param  \ProxyRequest\Dto\CouponUpdateRequest $couponUpdateRequest (required)
     * @param  string|null $ifMatch Strong ETag from the latest representation of this resource. (optional)
     * @param  string|null $acceptLanguage Preferred language for human-readable API errors. Supported languages: en, ru, uk, de, it, fr, es, zh-hans, ja. Regional language tags and quality weights are accepted; unsupported or omitted values use English. (optional, default to 'en')
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['replace'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function replaceRequest($id, $couponUpdateRequest, $ifMatch = null, $acceptLanguage = null, string $contentType = self::contentTypes['replace'][0])
    {

        // verify the required parameter 'id' is set
        if ($id === null || (is_array($id) && count($id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $id when calling replace'
            );
        }

        // verify the required parameter 'couponUpdateRequest' is set
        if ($couponUpdateRequest === null || (is_array($couponUpdateRequest) && count($couponUpdateRequest) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $couponUpdateRequest when calling replace'
            );
        }




        $resourcePath = '/coupons/{id}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;


        // header params
        if ($ifMatch !== null) {
            $headerParams['If-Match'] = ObjectSerializer::toHeaderValue($ifMatch);
        }
        // header params
        if ($acceptLanguage !== null) {
            $headerParams['Accept-Language'] = ObjectSerializer::toHeaderValue($acceptLanguage);
        }

        // path params
        if ($id !== null) {
            $resourcePath = str_replace(
                '{id}',
                ObjectSerializer::toPathValue($id),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($couponUpdateRequest)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \ProxyRequest\Support\Json::encode(ObjectSerializer::sanitizeForSerialization($couponUpdateRequest));
            } else {
                $httpBody = $couponUpdateRequest;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \ProxyRequest\Support\Json::encode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Authorization');
        if ($apiKey !== null) {
            $headers['Authorization'] = $apiKey;
        }
        // this endpoint requires Bearer (JWT) authentication (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'PUT',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation update
     *
     * Update a coupon
     *
     * @param  string $id A unique value identifying this Coupon. (required)
     * @param  string|null $ifMatch Strong ETag from the latest representation of this resource. (optional)
     * @param  string|null $acceptLanguage Preferred language for human-readable API errors. Supported languages: en, ru, uk, de, it, fr, es, zh-hans, ja. Regional language tags and quality weights are accepted; unsupported or omitted values use English. (optional, default to 'en')
     * @param  \ProxyRequest\Dto\PatchedCouponUpdateRequest|null $patchedCouponUpdateRequest patchedCouponUpdateRequest (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['update'] to see the possible values for this operation
     *
     * @throws \ProxyRequest\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \ProxyRequest\Dto\Coupon|\ProxyRequest\Dto\AffiliatesList401Response|\ProxyRequest\Dto\AffiliatesList401Response|\ProxyRequest\Dto\AffiliatesList401Response|\ProxyRequest\Dto\AffiliatesList401Response|\ProxyRequest\Dto\AffiliatesList401Response
     */
    public function update($id, $ifMatch = null, $acceptLanguage = null, $patchedCouponUpdateRequest = null, string $contentType = self::contentTypes['update'][0])
    {
        list($response) = $this->updateWithHttpInfo($id, $ifMatch, $acceptLanguage, $patchedCouponUpdateRequest, $contentType);
        return $response;
    }

    /**
     * Operation updateWithResponse
     *
     * @return \ProxyRequest\ApiResponse
     */
    public function updateWithResponse($id, $ifMatch = null, $acceptLanguage = null, $patchedCouponUpdateRequest = null, string $contentType = self::contentTypes['update'][0]): \ProxyRequest\ApiResponse
    {
        return \ProxyRequest\ApiResponse::fromHttpInfo($this->updateWithHttpInfo($id, $ifMatch, $acceptLanguage, $patchedCouponUpdateRequest, $contentType));
    }

    /**
     * Operation updateWithHttpInfo
     *
     * Update a coupon
     *
     * @param  string $id A unique value identifying this Coupon. (required)
     * @param  string|null $ifMatch Strong ETag from the latest representation of this resource. (optional)
     * @param  string|null $acceptLanguage Preferred language for human-readable API errors. Supported languages: en, ru, uk, de, it, fr, es, zh-hans, ja. Regional language tags and quality weights are accepted; unsupported or omitted values use English. (optional, default to 'en')
     * @param  \ProxyRequest\Dto\PatchedCouponUpdateRequest|null $patchedCouponUpdateRequest (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['update'] to see the possible values for this operation
     *
     * @throws \ProxyRequest\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \ProxyRequest\Dto\Coupon|\ProxyRequest\Dto\AffiliatesList401Response|\ProxyRequest\Dto\AffiliatesList401Response|\ProxyRequest\Dto\AffiliatesList401Response|\ProxyRequest\Dto\AffiliatesList401Response|\ProxyRequest\Dto\AffiliatesList401Response, HTTP status code, HTTP response headers (array of strings)
     */
    public function updateWithHttpInfo($id, $ifMatch = null, $acceptLanguage = null, $patchedCouponUpdateRequest = null, string $contentType = self::contentTypes['update'][0])
    {
        $request = $this->updateRequest($id, $ifMatch, $acceptLanguage, $patchedCouponUpdateRequest, $contentType);
        return \ProxyRequest\Support\ResponseHandler::send($this->client, $request, $this->createHttpClientOption(), array (
  200 => '\\ProxyRequest\\Dto\\Coupon',
));
    }

    /**
     * Operation updateAsync
     *
     * Update a coupon
     *
     * @param  string $id A unique value identifying this Coupon. (required)
     * @param  string|null $ifMatch Strong ETag from the latest representation of this resource. (optional)
     * @param  string|null $acceptLanguage Preferred language for human-readable API errors. Supported languages: en, ru, uk, de, it, fr, es, zh-hans, ja. Regional language tags and quality weights are accepted; unsupported or omitted values use English. (optional, default to 'en')
     * @param  \ProxyRequest\Dto\PatchedCouponUpdateRequest|null $patchedCouponUpdateRequest (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['update'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function updateAsync($id, $ifMatch = null, $acceptLanguage = null, $patchedCouponUpdateRequest = null, string $contentType = self::contentTypes['update'][0])
    {
        return $this->updateAsyncWithHttpInfo($id, $ifMatch, $acceptLanguage, $patchedCouponUpdateRequest, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation updateAsyncWithHttpInfo
     *
     * Update a coupon
     *
     * @param  string $id A unique value identifying this Coupon. (required)
     * @param  string|null $ifMatch Strong ETag from the latest representation of this resource. (optional)
     * @param  string|null $acceptLanguage Preferred language for human-readable API errors. Supported languages: en, ru, uk, de, it, fr, es, zh-hans, ja. Regional language tags and quality weights are accepted; unsupported or omitted values use English. (optional, default to 'en')
     * @param  \ProxyRequest\Dto\PatchedCouponUpdateRequest|null $patchedCouponUpdateRequest (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['update'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function updateAsyncWithHttpInfo($id, $ifMatch = null, $acceptLanguage = null, $patchedCouponUpdateRequest = null, string $contentType = self::contentTypes['update'][0])
    {
        $request = $this->updateRequest($id, $ifMatch, $acceptLanguage, $patchedCouponUpdateRequest, $contentType);
        return \ProxyRequest\Support\ResponseHandler::sendAsync($this->client, $request, $this->createHttpClientOption(), array (
  200 => '\\ProxyRequest\\Dto\\Coupon',
));
    }

    /**
     * Create request for operation 'update'
     *
     * @param  string $id A unique value identifying this Coupon. (required)
     * @param  string|null $ifMatch Strong ETag from the latest representation of this resource. (optional)
     * @param  string|null $acceptLanguage Preferred language for human-readable API errors. Supported languages: en, ru, uk, de, it, fr, es, zh-hans, ja. Regional language tags and quality weights are accepted; unsupported or omitted values use English. (optional, default to 'en')
     * @param  \ProxyRequest\Dto\PatchedCouponUpdateRequest|null $patchedCouponUpdateRequest (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['update'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function updateRequest($id, $ifMatch = null, $acceptLanguage = null, $patchedCouponUpdateRequest = null, string $contentType = self::contentTypes['update'][0])
    {

        // verify the required parameter 'id' is set
        if ($id === null || (is_array($id) && count($id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $id when calling update'
            );
        }





        $resourcePath = '/coupons/{id}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;


        // header params
        if ($ifMatch !== null) {
            $headerParams['If-Match'] = ObjectSerializer::toHeaderValue($ifMatch);
        }
        // header params
        if ($acceptLanguage !== null) {
            $headerParams['Accept-Language'] = ObjectSerializer::toHeaderValue($acceptLanguage);
        }

        // path params
        if ($id !== null) {
            $resourcePath = str_replace(
                '{id}',
                ObjectSerializer::toPathValue($id),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($patchedCouponUpdateRequest)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \ProxyRequest\Support\Json::encode(ObjectSerializer::sanitizeForSerialization($patchedCouponUpdateRequest));
            } else {
                $httpBody = $patchedCouponUpdateRequest;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \ProxyRequest\Support\Json::encode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Authorization');
        if ($apiKey !== null) {
            $headers['Authorization'] = $apiKey;
        }
        // this endpoint requires Bearer (JWT) authentication (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'PATCH',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [RequestOptions::HTTP_ERRORS => true];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        if ($this->config->getCertFile()) {
            $options[RequestOptions::CERT] = $this->config->getCertFile();
        }

        if ($this->config->getKeyFile()) {
            $options[RequestOptions::SSL_KEY] = $this->config->getKeyFile();
        }

        return $options;
    }

    private function handleResponseWithDataType(
        string $dataType,
        RequestInterface $request,
        ResponseInterface $response
    ): array {
        if ($dataType === '\SplFileObject') {
            $content = $response->getBody(); //stream goes to serializer
        } else {
            $content = (string) $response->getBody();
            if ($dataType !== 'string') {
                try {
                    $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                } catch (\JsonException $exception) {
                    throw new ApiException(
                        sprintf(
                            'Error JSON decoding server response (%s)',
                            $request->getUri()
                        ),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                        $content
                    );
                }
            }
        }

        return [
            ObjectSerializer::deserialize($content, $dataType, []),
            $response->getStatusCode(),
            $response->getHeaders()
        ];
    }

    private function responseWithinRangeCode(
        string $rangeCode,
        int $statusCode
    ): bool {
        $left = (int) ($rangeCode[0].'00');
        $right = (int) ($rangeCode[0].'99');

        return $statusCode >= $left && $statusCode <= $right;
    }
}
