<?php
/**
 * InvoiceCreateRequestGatewayEnum
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  ProxyRequest
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Proxy Public API
 *
 * Reference for the customer-facing HTTP API. Request and response examples use synthetic values but follow the payloads returned by the service. Authenticate customer requests with a JWT or API key in the Authorization header.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.23.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace ProxyRequest\Dto;
use \ProxyRequest\ObjectSerializer;

/**
 * InvoiceCreateRequestGatewayEnum Class Doc Comment
 *
 * @category Class
 * @description * &#x60;crypto&#x60; - crypto * &#x60;wallet&#x60; - wallet * &#x60;manual&#x60; - manual * &#x60;stripe&#x60; - stripe
 * @package  ProxyRequest
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class InvoiceCreateRequestGatewayEnum
{
    /**
     * Possible values of this enum
     */
    public const CRYPTO = 'crypto';

    public const WALLET = 'wallet';

    public const MANUAL = 'manual';

    public const STRIPE = 'stripe';

    public const UNKNOWN_DEFAULT_OPEN_API = 'unknown_default_open_api';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::CRYPTO,
            self::WALLET,
            self::MANUAL,
            self::STRIPE,
            self::UNKNOWN_DEFAULT_OPEN_API
        ];
    }
}


