<?php
/**
 * InvoiceGatewayEnum
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  ProxyRequest
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Proxy Public API
 *
 * Reference for the customer-facing HTTP API. Request and response examples use synthetic values but follow the payloads returned by the service. Authenticate customer requests with a JWT or API key in the Authorization header.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.23.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace ProxyRequest\Dto;
use \ProxyRequest\ObjectSerializer;

/**
 * InvoiceGatewayEnum Class Doc Comment
 *
 * @category Class
 * @description * &#x60;coinbase&#x60; - Coinbase * &#x60;cryptomus&#x60; - Cryptomus * &#x60;stripe&#x60; - Stripe * &#x60;coingate&#x60; - Coingate * &#x60;wallet&#x60; - Wallet * &#x60;manual&#x60; - Manual * &#x60;whitepay&#x60; - Whitepay * &#x60;wayforpay&#x60; - WayForPay * &#x60;usegateway&#x60; - UseGateway * &#x60;binance&#x60; - Binance Pay * &#x60;anymoney&#x60; - Any.Money * &#x60;coinpayments&#x60; - CoinPayments * &#x60;checkoutcom&#x60; - Checkout.com * &#x60;nowpayments&#x60; - NOWPayments * &#x60;btcpay&#x60; - BTCPay Server * &#x60;braintree&#x60; - Braintree * &#x60;monobank&#x60; - monobank * &#x60;liqpay&#x60; - LiqPay * &#x60;iyzico&#x60; - iyzico * &#x60;paytr&#x60; - PayTR * &#x60;payu&#x60; - PayU * &#x60;tpay&#x60; - Tpay * &#x60;przelewy24&#x60; - Przelewy24 * &#x60;gopay&#x60; - GoPay * &#x60;comgate&#x60; - Comgate * &#x60;monei&#x60; - MONEI * &#x60;redsys&#x60; - Redsys * &#x60;payplug&#x60; - PayPlug * &#x60;mollie&#x60; - Mollie * &#x60;unzer&#x60; - Unzer * &#x60;payone&#x60; - PAYONE * &#x60;nexi_xpay&#x60; - Nexi XPay * &#x60;halyk_epay&#x60; - Halyk ePay * &#x60;kaspi_pay&#x60; - Kaspi Pay * &#x60;vipps_mobilepay&#x60; - Vipps MobilePay * &#x60;paytrail&#x60; - Paytrail
 * @package  ProxyRequest
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class InvoiceGatewayEnum
{
    /**
     * Possible values of this enum
     */
    public const COINBASE = 'coinbase';

    public const CRYPTOMUS = 'cryptomus';

    public const STRIPE = 'stripe';

    public const COINGATE = 'coingate';

    public const WALLET = 'wallet';

    public const MANUAL = 'manual';

    public const WHITEPAY = 'whitepay';

    public const WAYFORPAY = 'wayforpay';

    public const USEGATEWAY = 'usegateway';

    public const BINANCE = 'binance';

    public const ANYMONEY = 'anymoney';

    public const COINPAYMENTS = 'coinpayments';

    public const CHECKOUTCOM = 'checkoutcom';

    public const NOWPAYMENTS = 'nowpayments';

    public const BTCPAY = 'btcpay';

    public const BRAINTREE = 'braintree';

    public const MONOBANK = 'monobank';

    public const LIQPAY = 'liqpay';

    public const IYZICO = 'iyzico';

    public const PAYTR = 'paytr';

    public const PAYU = 'payu';

    public const TPAY = 'tpay';

    public const PRZELEWY24 = 'przelewy24';

    public const GOPAY = 'gopay';

    public const COMGATE = 'comgate';

    public const MONEI = 'monei';

    public const REDSYS = 'redsys';

    public const PAYPLUG = 'payplug';

    public const MOLLIE = 'mollie';

    public const UNZER = 'unzer';

    public const PAYONE = 'payone';

    public const NEXI_XPAY = 'nexi_xpay';

    public const HALYK_EPAY = 'halyk_epay';

    public const KASPI_PAY = 'kaspi_pay';

    public const VIPPS_MOBILEPAY = 'vipps_mobilepay';

    public const PAYTRAIL = 'paytrail';

    public const UNKNOWN_DEFAULT_OPEN_API = 'unknown_default_open_api';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::COINBASE,
            self::CRYPTOMUS,
            self::STRIPE,
            self::COINGATE,
            self::WALLET,
            self::MANUAL,
            self::WHITEPAY,
            self::WAYFORPAY,
            self::USEGATEWAY,
            self::BINANCE,
            self::ANYMONEY,
            self::COINPAYMENTS,
            self::CHECKOUTCOM,
            self::NOWPAYMENTS,
            self::BTCPAY,
            self::BRAINTREE,
            self::MONOBANK,
            self::LIQPAY,
            self::IYZICO,
            self::PAYTR,
            self::PAYU,
            self::TPAY,
            self::PRZELEWY24,
            self::GOPAY,
            self::COMGATE,
            self::MONEI,
            self::REDSYS,
            self::PAYPLUG,
            self::MOLLIE,
            self::UNZER,
            self::PAYONE,
            self::NEXI_XPAY,
            self::HALYK_EPAY,
            self::KASPI_PAY,
            self::VIPPS_MOBILEPAY,
            self::PAYTRAIL,
            self::UNKNOWN_DEFAULT_OPEN_API
        ];
    }
}
