<?php
/**
 * LevelEnum
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  ProxyRequest
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Proxy Public API
 *
 * Reference for the customer-facing HTTP API. Request and response examples use synthetic values but follow the payloads returned by the service. Authenticate customer requests with a JWT or API key in the Authorization header.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.23.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace ProxyRequest\Dto;
use \ProxyRequest\ObjectSerializer;

/**
 * LevelEnum Class Doc Comment
 *
 * @category Class
 * @description * &#x60;standard&#x60; - Standard * &#x60;silver&#x60; - Silver * &#x60;gold&#x60; - Gold * &#x60;diamond&#x60; - Diamond
 * @package  ProxyRequest
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class LevelEnum
{
    /**
     * Possible values of this enum
     */
    public const STANDARD = 'standard';

    public const SILVER = 'silver';

    public const GOLD = 'gold';

    public const DIAMOND = 'diamond';

    public const UNKNOWN_DEFAULT_OPEN_API = 'unknown_default_open_api';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::STANDARD,
            self::SILVER,
            self::GOLD,
            self::DIAMOND,
            self::UNKNOWN_DEFAULT_OPEN_API
        ];
    }
}


