<?php
/**
 * TargetingOptions
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  ProxyRequest
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Proxy Public API
 *
 * Reference for the customer-facing HTTP API. Request and response examples use synthetic values but follow the payloads returned by the service. Authenticate customer requests with a JWT or API key in the Authorization header.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.23.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace ProxyRequest\Dto;

use \ArrayAccess;
use \ProxyRequest\ObjectSerializer;

/**
 * TargetingOptions Class Doc Comment
 *
 * @category Class
 * @package  ProxyRequest
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class TargetingOptions implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $openAPIModelName = 'TargetingOptions';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var string[]
     */
    protected static $openAPITypes = [
        'package' => 'string',
        'splitChar' => 'string',
        'valueChar' => 'string',
        'continent' => 'string',
        'country' => 'string',
        'region' => 'string',
        'city' => 'string',
        'asn' => 'string',
        'isp' => 'string',
        'username' => 'string',
        'pool' => 'string',
        'location' => 'string',
        'locationFormat' => 'string',
        'session' => 'string',
        'sessionModeTag' => 'string',
        'sessionTtl' => 'string',
        'sessionTtlFormat' => 'int',
        'os' => 'string',
        'osCombined' => 'bool',
        'osSplitChar' => 'string',
        'osLinux' => 'string',
        'osWindows' => 'string',
        'osIos' => 'string',
        'osMacos' => 'string',
        'osAndroid' => 'string'
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var string[]
     * @phpstan-var array<string, string|null>
     * @psalm-var array<string, string|null>
     */
    protected static $openAPIFormats = [
        'package' => null,
        'splitChar' => null,
        'valueChar' => null,
        'continent' => null,
        'country' => null,
        'region' => null,
        'city' => null,
        'asn' => null,
        'isp' => null,
        'username' => null,
        'pool' => null,
        'location' => null,
        'locationFormat' => null,
        'session' => null,
        'sessionModeTag' => null,
        'sessionTtl' => null,
        'sessionTtlFormat' => null,
        'os' => null,
        'osCombined' => null,
        'osSplitChar' => null,
        'osLinux' => null,
        'osWindows' => null,
        'osIos' => null,
        'osMacos' => null,
        'osAndroid' => null
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var boolean[]
     */
    protected static array $openAPINullables = [
        'package' => false,
        'splitChar' => false,
        'valueChar' => false,
        'continent' => false,
        'country' => false,
        'region' => false,
        'city' => false,
        'asn' => false,
        'isp' => false,
        'username' => false,
        'pool' => false,
        'location' => false,
        'locationFormat' => false,
        'session' => false,
        'sessionModeTag' => false,
        'sessionTtl' => false,
        'sessionTtlFormat' => false,
        'os' => false,
        'osCombined' => false,
        'osSplitChar' => false,
        'osLinux' => false,
        'osWindows' => false,
        'osIos' => false,
        'osMacos' => false,
        'osAndroid' => false
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var boolean[]
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'package' => 'package',
        'splitChar' => 'split_char',
        'valueChar' => 'value_char',
        'continent' => 'continent',
        'country' => 'country',
        'region' => 'region',
        'city' => 'city',
        'asn' => 'asn',
        'isp' => 'isp',
        'username' => 'username',
        'pool' => 'pool',
        'location' => 'location',
        'locationFormat' => 'location_format',
        'session' => 'session',
        'sessionModeTag' => 'session_mode_tag',
        'sessionTtl' => 'session_ttl',
        'sessionTtlFormat' => 'session_ttl_format',
        'os' => 'os',
        'osCombined' => 'os_combined',
        'osSplitChar' => 'os_split_char',
        'osLinux' => 'os_linux',
        'osWindows' => 'os_windows',
        'osIos' => 'os_ios',
        'osMacos' => 'os_macos',
        'osAndroid' => 'os_android'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'package' => 'setPackage',
        'splitChar' => 'setSplitChar',
        'valueChar' => 'setValueChar',
        'continent' => 'setContinent',
        'country' => 'setCountry',
        'region' => 'setRegion',
        'city' => 'setCity',
        'asn' => 'setAsn',
        'isp' => 'setIsp',
        'username' => 'setUsername',
        'pool' => 'setPool',
        'location' => 'setLocation',
        'locationFormat' => 'setLocationFormat',
        'session' => 'setSession',
        'sessionModeTag' => 'setSessionModeTag',
        'sessionTtl' => 'setSessionTtl',
        'sessionTtlFormat' => 'setSessionTtlFormat',
        'os' => 'setOs',
        'osCombined' => 'setOsCombined',
        'osSplitChar' => 'setOsSplitChar',
        'osLinux' => 'setOsLinux',
        'osWindows' => 'setOsWindows',
        'osIos' => 'setOsIos',
        'osMacos' => 'setOsMacos',
        'osAndroid' => 'setOsAndroid'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'package' => 'getPackage',
        'splitChar' => 'getSplitChar',
        'valueChar' => 'getValueChar',
        'continent' => 'getContinent',
        'country' => 'getCountry',
        'region' => 'getRegion',
        'city' => 'getCity',
        'asn' => 'getAsn',
        'isp' => 'getIsp',
        'username' => 'getUsername',
        'pool' => 'getPool',
        'location' => 'getLocation',
        'locationFormat' => 'getLocationFormat',
        'session' => 'getSession',
        'sessionModeTag' => 'getSessionModeTag',
        'sessionTtl' => 'getSessionTtl',
        'sessionTtlFormat' => 'getSessionTtlFormat',
        'os' => 'getOs',
        'osCombined' => 'getOsCombined',
        'osSplitChar' => 'getOsSplitChar',
        'osLinux' => 'getOsLinux',
        'osWindows' => 'getOsWindows',
        'osIos' => 'getOsIos',
        'osMacos' => 'getOsMacos',
        'osAndroid' => 'getOsAndroid'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('package', $data ?? [], null);
        $this->setIfExists('splitChar', $data ?? [], null);
        $this->setIfExists('valueChar', $data ?? [], null);
        $this->setIfExists('continent', $data ?? [], null);
        $this->setIfExists('country', $data ?? [], null);
        $this->setIfExists('region', $data ?? [], null);
        $this->setIfExists('city', $data ?? [], null);
        $this->setIfExists('asn', $data ?? [], null);
        $this->setIfExists('isp', $data ?? [], null);
        $this->setIfExists('username', $data ?? [], null);
        $this->setIfExists('pool', $data ?? [], null);
        $this->setIfExists('location', $data ?? [], null);
        $this->setIfExists('locationFormat', $data ?? [], null);
        $this->setIfExists('session', $data ?? [], null);
        $this->setIfExists('sessionModeTag', $data ?? [], null);
        $this->setIfExists('sessionTtl', $data ?? [], null);
        $this->setIfExists('sessionTtlFormat', $data ?? [], null);
        $this->setIfExists('os', $data ?? [], null);
        $this->setIfExists('osCombined', $data ?? [], null);
        $this->setIfExists('osSplitChar', $data ?? [], null);
        $this->setIfExists('osLinux', $data ?? [], null);
        $this->setIfExists('osWindows', $data ?? [], null);
        $this->setIfExists('osIos', $data ?? [], null);
        $this->setIfExists('osMacos', $data ?? [], null);
        $this->setIfExists('osAndroid', $data ?? [], null);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['package'] === null) {
            $invalidProperties[] = "'package' can't be null";
        }
        if ($this->container['splitChar'] === null) {
            $invalidProperties[] = "'splitChar' can't be null";
        }
        if ($this->container['valueChar'] === null) {
            $invalidProperties[] = "'valueChar' can't be null";
        }
        if ($this->container['continent'] === null) {
            $invalidProperties[] = "'continent' can't be null";
        }
        if ($this->container['country'] === null) {
            $invalidProperties[] = "'country' can't be null";
        }
        if ($this->container['region'] === null) {
            $invalidProperties[] = "'region' can't be null";
        }
        if ($this->container['city'] === null) {
            $invalidProperties[] = "'city' can't be null";
        }
        if ($this->container['asn'] === null) {
            $invalidProperties[] = "'asn' can't be null";
        }
        if ($this->container['isp'] === null) {
            $invalidProperties[] = "'isp' can't be null";
        }
        if ($this->container['username'] === null) {
            $invalidProperties[] = "'username' can't be null";
        }
        if ($this->container['pool'] === null) {
            $invalidProperties[] = "'pool' can't be null";
        }
        if ($this->container['location'] === null) {
            $invalidProperties[] = "'location' can't be null";
        }
        if ($this->container['locationFormat'] === null) {
            $invalidProperties[] = "'locationFormat' can't be null";
        }
        if ($this->container['session'] === null) {
            $invalidProperties[] = "'session' can't be null";
        }
        if ($this->container['sessionModeTag'] === null) {
            $invalidProperties[] = "'sessionModeTag' can't be null";
        }
        if ($this->container['sessionTtl'] === null) {
            $invalidProperties[] = "'sessionTtl' can't be null";
        }
        if ($this->container['sessionTtlFormat'] === null) {
            $invalidProperties[] = "'sessionTtlFormat' can't be null";
        }
        if ($this->container['os'] === null) {
            $invalidProperties[] = "'os' can't be null";
        }
        if ($this->container['osCombined'] === null) {
            $invalidProperties[] = "'osCombined' can't be null";
        }
        if ($this->container['osSplitChar'] === null) {
            $invalidProperties[] = "'osSplitChar' can't be null";
        }
        if ($this->container['osLinux'] === null) {
            $invalidProperties[] = "'osLinux' can't be null";
        }
        if ($this->container['osWindows'] === null) {
            $invalidProperties[] = "'osWindows' can't be null";
        }
        if ($this->container['osIos'] === null) {
            $invalidProperties[] = "'osIos' can't be null";
        }
        if ($this->container['osMacos'] === null) {
            $invalidProperties[] = "'osMacos' can't be null";
        }
        if ($this->container['osAndroid'] === null) {
            $invalidProperties[] = "'osAndroid' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets package
     *
     * @return string
     */
    public function getPackage()
    {
        return $this->container['package'];
    }

    /**
     * Sets package
     *
     * @param string $package package
     *
     * @return self
     */
    public function setPackage($package)
    {
        if (is_null($package)) {
            throw new \InvalidArgumentException('non-nullable package cannot be null');
        }
        $this->container['package'] = $package;

        return $this;
    }

    /**
     * Gets splitChar
     *
     * @return string
     */
    public function getSplitChar()
    {
        return $this->container['splitChar'];
    }

    /**
     * Sets splitChar
     *
     * @param string $splitChar splitChar
     *
     * @return self
     */
    public function setSplitChar($splitChar)
    {
        if (is_null($splitChar)) {
            throw new \InvalidArgumentException('non-nullable splitChar cannot be null');
        }
        $this->container['splitChar'] = $splitChar;

        return $this;
    }

    /**
     * Gets valueChar
     *
     * @return string
     */
    public function getValueChar()
    {
        return $this->container['valueChar'];
    }

    /**
     * Sets valueChar
     *
     * @param string $valueChar valueChar
     *
     * @return self
     */
    public function setValueChar($valueChar)
    {
        if (is_null($valueChar)) {
            throw new \InvalidArgumentException('non-nullable valueChar cannot be null');
        }
        $this->container['valueChar'] = $valueChar;

        return $this;
    }

    /**
     * Gets continent
     *
     * @return string
     */
    public function getContinent()
    {
        return $this->container['continent'];
    }

    /**
     * Sets continent
     *
     * @param string $continent continent
     *
     * @return self
     */
    public function setContinent($continent)
    {
        if (is_null($continent)) {
            throw new \InvalidArgumentException('non-nullable continent cannot be null');
        }
        $this->container['continent'] = $continent;

        return $this;
    }

    /**
     * Gets country
     *
     * @return string
     */
    public function getCountry()
    {
        return $this->container['country'];
    }

    /**
     * Sets country
     *
     * @param string $country country
     *
     * @return self
     */
    public function setCountry($country)
    {
        if (is_null($country)) {
            throw new \InvalidArgumentException('non-nullable country cannot be null');
        }
        $this->container['country'] = $country;

        return $this;
    }

    /**
     * Gets region
     *
     * @return string
     */
    public function getRegion()
    {
        return $this->container['region'];
    }

    /**
     * Sets region
     *
     * @param string $region region
     *
     * @return self
     */
    public function setRegion($region)
    {
        if (is_null($region)) {
            throw new \InvalidArgumentException('non-nullable region cannot be null');
        }
        $this->container['region'] = $region;

        return $this;
    }

    /**
     * Gets city
     *
     * @return string
     */
    public function getCity()
    {
        return $this->container['city'];
    }

    /**
     * Sets city
     *
     * @param string $city city
     *
     * @return self
     */
    public function setCity($city)
    {
        if (is_null($city)) {
            throw new \InvalidArgumentException('non-nullable city cannot be null');
        }
        $this->container['city'] = $city;

        return $this;
    }

    /**
     * Gets asn
     *
     * @return string
     */
    public function getAsn()
    {
        return $this->container['asn'];
    }

    /**
     * Sets asn
     *
     * @param string $asn asn
     *
     * @return self
     */
    public function setAsn($asn)
    {
        if (is_null($asn)) {
            throw new \InvalidArgumentException('non-nullable asn cannot be null');
        }
        $this->container['asn'] = $asn;

        return $this;
    }

    /**
     * Gets isp
     *
     * @return string
     */
    public function getIsp()
    {
        return $this->container['isp'];
    }

    /**
     * Sets isp
     *
     * @param string $isp isp
     *
     * @return self
     */
    public function setIsp($isp)
    {
        if (is_null($isp)) {
            throw new \InvalidArgumentException('non-nullable isp cannot be null');
        }
        $this->container['isp'] = $isp;

        return $this;
    }

    /**
     * Gets username
     *
     * @return string
     */
    public function getUsername()
    {
        return $this->container['username'];
    }

    /**
     * Sets username
     *
     * @param string $username username
     *
     * @return self
     */
    public function setUsername($username)
    {
        if (is_null($username)) {
            throw new \InvalidArgumentException('non-nullable username cannot be null');
        }
        $this->container['username'] = $username;

        return $this;
    }

    /**
     * Gets pool
     *
     * @return string
     */
    public function getPool()
    {
        return $this->container['pool'];
    }

    /**
     * Sets pool
     *
     * @param string $pool pool
     *
     * @return self
     */
    public function setPool($pool)
    {
        if (is_null($pool)) {
            throw new \InvalidArgumentException('non-nullable pool cannot be null');
        }
        $this->container['pool'] = $pool;

        return $this;
    }

    /**
     * Gets location
     *
     * @return string
     */
    public function getLocation()
    {
        return $this->container['location'];
    }

    /**
     * Sets location
     *
     * @param string $location location
     *
     * @return self
     */
    public function setLocation($location)
    {
        if (is_null($location)) {
            throw new \InvalidArgumentException('non-nullable location cannot be null');
        }
        $this->container['location'] = $location;

        return $this;
    }

    /**
     * Gets locationFormat
     *
     * @return string
     */
    public function getLocationFormat()
    {
        return $this->container['locationFormat'];
    }

    /**
     * Sets locationFormat
     *
     * @param string $locationFormat locationFormat
     *
     * @return self
     */
    public function setLocationFormat($locationFormat)
    {
        if (is_null($locationFormat)) {
            throw new \InvalidArgumentException('non-nullable locationFormat cannot be null');
        }
        $this->container['locationFormat'] = $locationFormat;

        return $this;
    }

    /**
     * Gets session
     *
     * @return string
     */
    public function getSession()
    {
        return $this->container['session'];
    }

    /**
     * Sets session
     *
     * @param string $session session
     *
     * @return self
     */
    public function setSession($session)
    {
        if (is_null($session)) {
            throw new \InvalidArgumentException('non-nullable session cannot be null');
        }
        $this->container['session'] = $session;

        return $this;
    }

    /**
     * Gets sessionModeTag
     *
     * @return string
     */
    public function getSessionModeTag()
    {
        return $this->container['sessionModeTag'];
    }

    /**
     * Sets sessionModeTag
     *
     * @param string $sessionModeTag sessionModeTag
     *
     * @return self
     */
    public function setSessionModeTag($sessionModeTag)
    {
        if (is_null($sessionModeTag)) {
            throw new \InvalidArgumentException('non-nullable sessionModeTag cannot be null');
        }
        $this->container['sessionModeTag'] = $sessionModeTag;

        return $this;
    }

    /**
     * Gets sessionTtl
     *
     * @return string
     */
    public function getSessionTtl()
    {
        return $this->container['sessionTtl'];
    }

    /**
     * Sets sessionTtl
     *
     * @param string $sessionTtl sessionTtl
     *
     * @return self
     */
    public function setSessionTtl($sessionTtl)
    {
        if (is_null($sessionTtl)) {
            throw new \InvalidArgumentException('non-nullable sessionTtl cannot be null');
        }
        $this->container['sessionTtl'] = $sessionTtl;

        return $this;
    }

    /**
     * Gets sessionTtlFormat
     *
     * @return int
     */
    public function getSessionTtlFormat()
    {
        return $this->container['sessionTtlFormat'];
    }

    /**
     * Sets sessionTtlFormat
     *
     * @param int $sessionTtlFormat sessionTtlFormat
     *
     * @return self
     */
    public function setSessionTtlFormat($sessionTtlFormat)
    {
        if (is_null($sessionTtlFormat)) {
            throw new \InvalidArgumentException('non-nullable sessionTtlFormat cannot be null');
        }
        $this->container['sessionTtlFormat'] = $sessionTtlFormat;

        return $this;
    }

    /**
     * Gets os
     *
     * @return string
     */
    public function getOs()
    {
        return $this->container['os'];
    }

    /**
     * Sets os
     *
     * @param string $os os
     *
     * @return self
     */
    public function setOs($os)
    {
        if (is_null($os)) {
            throw new \InvalidArgumentException('non-nullable os cannot be null');
        }
        $this->container['os'] = $os;

        return $this;
    }

    /**
     * Gets osCombined
     *
     * @return bool
     */
    public function getOsCombined()
    {
        return $this->container['osCombined'];
    }

    /**
     * Sets osCombined
     *
     * @param bool $osCombined osCombined
     *
     * @return self
     */
    public function setOsCombined($osCombined)
    {
        if (is_null($osCombined)) {
            throw new \InvalidArgumentException('non-nullable osCombined cannot be null');
        }
        $this->container['osCombined'] = $osCombined;

        return $this;
    }

    /**
     * Gets osSplitChar
     *
     * @return string
     */
    public function getOsSplitChar()
    {
        return $this->container['osSplitChar'];
    }

    /**
     * Sets osSplitChar
     *
     * @param string $osSplitChar osSplitChar
     *
     * @return self
     */
    public function setOsSplitChar($osSplitChar)
    {
        if (is_null($osSplitChar)) {
            throw new \InvalidArgumentException('non-nullable osSplitChar cannot be null');
        }
        $this->container['osSplitChar'] = $osSplitChar;

        return $this;
    }

    /**
     * Gets osLinux
     *
     * @return string
     */
    public function getOsLinux()
    {
        return $this->container['osLinux'];
    }

    /**
     * Sets osLinux
     *
     * @param string $osLinux osLinux
     *
     * @return self
     */
    public function setOsLinux($osLinux)
    {
        if (is_null($osLinux)) {
            throw new \InvalidArgumentException('non-nullable osLinux cannot be null');
        }
        $this->container['osLinux'] = $osLinux;

        return $this;
    }

    /**
     * Gets osWindows
     *
     * @return string
     */
    public function getOsWindows()
    {
        return $this->container['osWindows'];
    }

    /**
     * Sets osWindows
     *
     * @param string $osWindows osWindows
     *
     * @return self
     */
    public function setOsWindows($osWindows)
    {
        if (is_null($osWindows)) {
            throw new \InvalidArgumentException('non-nullable osWindows cannot be null');
        }
        $this->container['osWindows'] = $osWindows;

        return $this;
    }

    /**
     * Gets osIos
     *
     * @return string
     */
    public function getOsIos()
    {
        return $this->container['osIos'];
    }

    /**
     * Sets osIos
     *
     * @param string $osIos osIos
     *
     * @return self
     */
    public function setOsIos($osIos)
    {
        if (is_null($osIos)) {
            throw new \InvalidArgumentException('non-nullable osIos cannot be null');
        }
        $this->container['osIos'] = $osIos;

        return $this;
    }

    /**
     * Gets osMacos
     *
     * @return string
     */
    public function getOsMacos()
    {
        return $this->container['osMacos'];
    }

    /**
     * Sets osMacos
     *
     * @param string $osMacos osMacos
     *
     * @return self
     */
    public function setOsMacos($osMacos)
    {
        if (is_null($osMacos)) {
            throw new \InvalidArgumentException('non-nullable osMacos cannot be null');
        }
        $this->container['osMacos'] = $osMacos;

        return $this;
    }

    /**
     * Gets osAndroid
     *
     * @return string
     */
    public function getOsAndroid()
    {
        return $this->container['osAndroid'];
    }

    /**
     * Sets osAndroid
     *
     * @param string $osAndroid osAndroid
     *
     * @return self
     */
    public function setOsAndroid($osAndroid)
    {
        if (is_null($osAndroid)) {
            throw new \InvalidArgumentException('non-nullable osAndroid cannot be null');
        }
        $this->container['osAndroid'] = $osAndroid;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


